const languages = [
    { code: "af-ZA", name: "Afrikaans" },
    { code: "am-ET", name: "አማርኛ (Amharic)" },
    { code: "az-AZ", name: "Azərbaycanca" },
    { code: "bn-BD,বাংলাদেশ", name: "বাংলা (Bangla)" },
    { code: "id-ID", name: "Bahasa Indonesia" },
    { code: "ms-MY", name: "Bahasa Melayu" },
    { code: "ca-ES", name: "Català" },
    { code: "cs-CZ", name: "Čeština" },
    { code: "da-DK", name: "Dansk" },
    { code: "de-DE", name: "Deutsch" },
    { code: "en-US", name: "English" },
    { code: "es-AR,Argentina", name: "Español" },
    { code: "eu-ES", name: "Euskara" },
    { code: "fil-PH", name: "Filipino" },
    { code: "fr-FR", name: "Français" },
    { code: "jv-ID", name: "Basa Jawa" },
    { code: "gl-ES", name: "Galego" },
    { code: "gu-IN", name: "ગુજરાતી (Gujarati)" },
    { code: "hr-HR", name: "Hrvatski" },
    { code: "zu-ZA", name: "IsiZulu" },
    { code: "is-IS", name: "Íslenska" },
    { code: "it-IT,Italia", name: "Italiano" },
    { code: "kn-IN", name: "ಕನ್ನಡ (Kannaḍa)" },
    { code: "km-KH", name: "ភាសាខ្មែរ (Khmer)" },
    { code: "lv-LV", name: "Latviešu" },
    { code: "lt-LT", name: "Lietuvių" },
    { code: "ml-IN", name: "മലയാളം (Malayalam)" },
    { code: "mr-IN", name: "मराठी (Marathi)" },
    { code: "hu-HU", name: "Magyar" },
    { code: "lo-LA", name: "ລາວ (Lao)" },
    { code: "nl-NL", name: "Nederlands" },
    { code: "ne-NP", name: "नेपाली भाषा (Nepali )" },
    { code: "nb-NO", name: "Norsk bokmål" },
    { code: "pl-PL", name: "Polski" },
    { code: "pt-BR,Brasil", name: "Português" },
    { code: "ro-RO", name: "Română" },
    { code: "si-LK", name: "සිංහල (Sinhala)" },
    { code: "sl-SI", name: "Slovenščina" },
    { code: "su-ID", name: "Basa Sunda" },
    { code: "sk-SK", name: "Slovenčina" },
    { code: "fi-FI", name: "Suomi" },
    { code: "sv-SE", name: "Svenska" },
    { code: "sw-TZ,Tanzania", name: "Kiswahili" },
    { code: "ka-GE", name: "ქართული (Georgian)" },
    { code: "hy-AM", name: "Հայերեն (Armenian)" },
    { code: "ta-IN,இந்தியா", name: "தமிழ் (Tamil)" },
    { code: "te-IN", name: "తెలుగు (Telugu)" },
    { code: "vi-VN", name: "Tiếng Việt (Vietnamese)" },
    { code: "tr-TR", name: "Türkçe (Turkish)" },
    { code: "ur-PK,پاکستان", name: "اُردُو (Urdu)" },
    { code: "el-GR", name: "Ελληνικά (Greek)" },
    { code: "bg-BG", name: "български (Bulgarian)" },
    { code: "ru-RU", name: "Pусский (Russian)" },
    { code: "sr-RS", name: "Српски (Serbian)" },
    { code: "uk-UA", name: "Українська (Ukrainian)" },
    { code: "ko-KR", name: "한국어 (Korean)" },
    { code: "cmn-Hans-CN,普通话 (中国大陆)", name: "中文 (Chinese)" },
    { code: "ja-JP", name: "日本語 (Japanese)" },
    { code: "hi-IN", name: "हिन्दी (Hindi)" },
    { code: "th-TH", name: "ภาษาไทย (Thai)" },
];
export default languages
